DROP SEQUENCE SEQ_TAG;
CREATE SEQUENCE SEQ_TAG START WITH 1 INCREMENT BY 1;
DROP SEQUENCE SEQ_TEMPLATE;
CREATE SEQUENCE SEQ_TEMPLATE START WITH 1 INCREMENT BY 1;
DROP SEQUENCE SEQ_USER;
CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1;
DROP SEQUENCE SEQ_WALLET;
CREATE SEQUENCE SEQ_WALLET START WITH 1 INCREMENT BY 1;

