CREATE TABLE TEMPLATE
(
    TEMPLATE_ID BIGINT       NOT NULL,
    NAME        VARCHAR(255) NULL,
    VALUE       VARCHAR(255) NULL,
    WALLET_ID   BIGINT       NOT NULL,
    CONSTRAINT PK_TEMPLATE PRIMARY KEY (TEMPLATE_ID)
);

CREATE TABLE TEMPLATE_TAG
(
    TAG_ID      BIGINT NOT NULL,
    TEMPLATE_ID BIGINT NOT NULL
);

ALTER TABLE TEMPLATE_TAG
    ADD CONSTRAINT UC_TEMPLATE_TAG_TAG UNIQUE (TAG_ID);

ALTER TABLE TEMPLATE
    ADD CONSTRAINT FK_TEMPLATE_ON_WALLET FOREIGN KEY (WALLET_ID) REFERENCES WALLET (WALLET_ID);

ALTER TABLE TEMPLATE_TAG
    ADD CONSTRAINT FK_TEMTAG_ON_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG (TAG_ID);

ALTER TABLE TEMPLATE_TAG
    ADD CONSTRAINT FK_TEMTAG_ON_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATE (TEMPLATE_ID);